version: "3.8"
services:
  # app:
  #   container_name: "sipartan-be"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - SECRETKEY=12345
  #     - DB_HOST=db
  #     - DB_USER=postgres
  #     - DB_PASS=postgres
  #     - DB_NAME=sipartan-db-local
  #     - DB_PORT=5432
  #   ports:
  #     - "9001:8081"
  #   networks:
  #     - default
  #   depends_on:
  #     - db

  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sipartan-db-local
    ports:
      - "5433:5432"
    volumes:
      - pgdata-postgis:/var/lib/postgresql/data
    networks:
      - default

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9002"
    ports:
      - "9000:9000" # S3 API
      - "9002:9002" # MinIO Console
    volumes:
      - miniodata:/data
    networks:
      - default

networks:
  default:

volumes:
  pgdata-postgis:
  miniodata:
